### ISSUE TITLE
Community Cloud Exam out of date

### ISSUE THREAD

**Issue by meighan** [SCuvanov/SalesforceCertScoreCalculator#23]
Percentages can be verified here: https://trailhead.salesforce.com/help?article=Salesforce-Certified-Experience-Cloud-Consultant-Exam-Guide

Experience Cloud Basics: 8%
Sharing, Visibility, and Licensing: 17%
Branding, Personalization, and Content: 15%
Templates and Themes: 10%
User Creation and Authentication: 13%
Adoption and Analytics: 5%
Administration, Setup and Configuration: 25%
Customization Considerations, and Limitations: 7%

BTW love the tool! Use it myself, for mentoring and with my user group and anyone that will listen 😅

**Comment by jesperklang** [comment]
Created PR #24 with the new changes! 😉
