### ISSUE TITLE
Marketing Cloud Consultant is outdated

### ISSUE THREAD

**Issue by duyduc27** [SCuvanov/SalesforceCertScoreCalculator#27]
You can refer the exam outline here: [https://trailhead.salesforce.com/en/help?article=Salesforce-Certified-Marketing-Cloud-Consultant-Exam-Guide](https://trailhead.salesforce.com/en/help?article=Salesforce-Certified-Marketing-Cloud-Consultant-Exam-Guide)

**Comment by jesperklang** [comment]
Added the new changes in the PR #28
