### ISSUE TITLE
Development Lifecycle And Deployment Designer -- Out of date

### ISSUE THREAD

**Issue by BreakingGood** [SCuvanov/SalesforceCertScoreCalculator#31]
This cert has had some changes to its exam structure, you can see the weights here:

https://trailhead.salesforce.com/en/help?article=Salesforce-Certified-Development-Lifecycle-and-Deployment-Designer-Exam-Guide

**Comment by SCuvanov** [comment]
Thanks. This should be updated now. Let me know if anything else is wrong.
